name: Custom Action Demo
on: 
  push:
    branches:
      - main

jobs:
  greet-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Calling custom action yml
        id: greet
        uses: javedfgiet/greeting-action@v1.0
        with:
          username: JavedAhmad

      - name: Use action output
        run: echo "Action says - ${{ steps.greet.outputs.message }}"
